import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  // tutorialSidebar: [
    // 'intro',
    // 'hello',
    // {
    //   type: 'category',
    //   label: 'Tutorial',
    //   items: ['tutorial-basics/create-a-document'],
    // },
  // ],
};

export default sidebars;

// sidebars.js
// module.exports = {
//   docsSidebar: [
//     'intro', // docs/intro.md
//     {
//       type: 'category',
//       label: 'Getting Started',
//       collapsed: false,
//       items: [
//         'getting-started/installation',
//         'getting-started/quick-start',
//         'getting-started/project-structure',
//       ],
//     },
//     {
//       type: 'category',
//       label: 'Core Concepts',
//       collapsed: false,
//       items: [
//         'core/components',
//         'core/state-management',
//         'core/lifecycle-hooks',
//         'core/events',
//       ],
//     },
//     {
//       type: 'category',
//       label: 'Advanced Features',
//       collapsed: true,
//       items: [
//         'advanced/routing',
//         'advanced/global-state',
//         'advanced/styling',
//         'advanced/plugins',
//       ],
//     },
//     {
//       type: 'category',
//       label: 'CLI & Tooling',
//       collapsed: true,
//       items: [
//         'cli/scaffolding',
//         'cli/dev-server',
//         'cli/build-system',
//       ],
//     },
//     {
//       type: 'category',
//       label: 'Guides & Examples',
//       collapsed: true,
//       items: [
//         'guides/example-app',
//         'guides/testing',
//         'guides/performance-tips',
//       ],
//     },
//     {
//       type: 'category',
//       label: 'API Reference',
//       collapsed: true,
//       items: [
//         'api/component-api',
//         'api/state-api',
//         'api/events-api',
//       ],
//     },
//     {
//       type: 'category',
//       label: 'Miscellaneous',
//       collapsed: true,
//       items: [
//         'misc/faq',
//         'misc/contributing',
//         'misc/changelog',
//       ],
//     },
//   ],
// };
